# Generated by Django 5.1.2 on 2024-10-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postare',
            index=models.Index(fields=['-publicare'], name='road_postar_publica_b5bce6_idx'),
        ),
    ]
