# Generated by Django 5.1.2 on 2024-10-31 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0003_locatie_organizator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambalaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30, unique=True)),
                ('material', models.CharField(choices=[('plastic', 'Plastic'), ('hartie', 'Hartie'), ('carton', 'Carton')], default='plastic', max_length=10)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30, unique=True)),
                ('calorii', models.IntegerField()),
                ('unitate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prajitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('comanda speciala', 'Comanda Speciala'), ('aniversara', 'Aniversara'), ('editie limitata', 'Editie Limitata'), ('pentru copii', 'Pentru Copii'), ('dietetica', 'Dietetica'), ('comuna', 'Comuna')], default='comuna', max_length=20)),
                ('tip_produs', models.CharField(choices=[('cofetarie', 'Cofetarie'), ('patiserie', 'Patiserie'), ('gelaterie', 'Gelaterie')], default='cofetarie', max_length=20)),
                ('nume', models.CharField(max_length=50, unique=True)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gramaj', models.IntegerField()),
                ('calorii', models.IntegerField()),
                ('merge_diabet', models.BooleanField(default=False)),
                ('imagine', models.CharField(max_length=300, null=True)),
                ('data_adaugare', models.DateTimeField()),
                ('ambalaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.ambalaj')),
                ('ingredient', models.ManyToManyField(to='road.ingredient')),
            ],
        ),
    ]
