# Generated by Django 5.1.2 on 2024-11-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0004_ambalaj_ingredient_prajitura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frecventa', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fabricant', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=10)),
                ('model', models.TextField()),
                ('generatie', models.IntegerField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlacaGrafica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cores', models.IntegerField()),
                ('fabricant', models.CharField(max_length=100)),
                ('frecventa', models.IntegerField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensiune', models.PositiveIntegerField()),
                ('fabricant', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataLansare', models.DateField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriere', models.TextField()),
                ('peStoc', models.BooleanField()),
                ('RAM', models.IntegerField()),
                ('idProcesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.cpu')),
                ('idSSD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.ssd')),
            ],
        ),
    ]
