# Generated by Django 5.1.2 on 2024-11-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0005_cooler_cpu_placagrafica_ssd_calculator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prajitura',
            name='ambalaj',
        ),
        migrations.RemoveField(
            model_name='prajitura',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='Locatie',
        ),
        migrations.DeleteModel(
            name='Organizator',
        ),
        migrations.DeleteModel(
            name='Postare',
        ),
        migrations.DeleteModel(
            name='Ambalaj',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Prajitura',
        ),
    ]
